// Importing Font and globals css
import { Outfit } from "next/font/google"
import "./globals.css"

// Creating outfit font
const outfit = Outfit({ weight: ["300", "400", "500", "700"], subsets: ["latin"], display: "swap" })

// Exporting Metadata
export const metadata = {
  title: "Insightify",
  description: "Generated by create next app"
}

// Exporting RootLayout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>{children}</body>
    </html>
  )
}
